### ISSUE TITLE
Explain why KDE is the only option for live environment in FAQ

### ISSUE THREAD

**Issue by 1Naim** [CachyOS/wiki#46]
It might be worth adding these to FAQ for users to better understand why these aren't an option during installation process. AFAIK the reasons why haven't been clearly mentioned anywhere, and this could give better transparency on the thinking process and metholody of the CachyOS team.

Why this issue was opened:
- [This user has raised valid points about GNOME and KDE being the 2 most popular DEs in Linux, but GNOME isn't provided as live environment](https://discord.com/channels/862292009423470592/862294383470051348/1270609721639964745)

**Comment by vnepogodin** [comment]
> It might be worth adding these to FAQ for users to better understand why these aren't an option during installation process. AFAIK the reasons why haven't been clearly mentioned anywhere, and this could give better transparency on the thinking process and metholody of the CachyOS team.

Might also mention that live iso is not meant for testing, and only thought for recovery(chroot etc) and installation
