### ISSUE TITLE
firewalld instead of ufw

### ISSUE THREAD

**Issue by dougg0k** [CachyOS/wiki#79]
Hi,

I would like to suggest changing the default firewall to firewalld instead of ufw. 

I previously used ufw, but I learned that it is bypassed and have no effect on container tools like docker, podman, etc.., not sure if it's relevant to you to consider this.

https://wiki.archlinux.org/title/Firewalld

https://www.google.com/search?q=ufw+containers+bypass

https://wiki.cachyos.org/configuration/post_install_setup/#2-configuring-firewall-ufw

**Comment by ptr1337** [comment]
We have explicitly changed to ufw, because its easier to user to handle this and also plasma-firewall has a GUI for this.
We are not planning to change back for firewalld. Expierenced users can change anyways to the firewall they want.

firewalld also exposes as default docker. You need to do extra rules, like with ufw.

**Comment by v1993** [comment]
In case you ever decide to reconsider this, I've personally found firewalld's multi-zone functionality a lot more versatile than what ufw allows - networkmanager integration allowing to set per-connection zones alone is enough of a reason to switch back for me. Also, firewalld has a much bigger list of known services and is configurable from plasma settings as well (to a limited extent, admittedly).

**Comment by dougg0k** [comment]
ufw is in fact way easier to use, I suppose what firewalld lacks is clarity in how to use it, be from the UI or command line. Maybe a wiki page detailing all the main important parts would be something.

**Comment by v1993** [comment]
That's fair, it definitely took me a bit of googling to figure out how to properly use firewalld compared to basically obvious, if lacking, UX of UFW; I'd say the [Endeavour OS article](https://discovery.endeavouros.com/applications/firewalld/2022/03/) about firewalld is an okay starting point, but a more comprehensive manual wouldn't hurt either.
